export default {
  SITE_DESCRIPTION: 'description',
  EXAMPLE_URL: 'exampleUrl',
  SUBMIT_BTN: 'submitBtn',
  CLOSE_MODAL_BTN: 'closeModalBtn',
  OPEN_ARTICLE: 'openFullArticle',
  CREATED_BY: 'createdBy',
  CHANNELS_TITLE: 'channelsTitle',
  FEED_TITLE: 'feedTitle',
  OPEN_MODAL_BTN: 'openModalBtn',
  RSS_HAS_BEEN_LOADED: 'successMsg',
  RSS_IS_LOADING: 'loadingMsg',
  URL_HAS_NO_RSS: 'noRss',
  NETWORK_ERROR: 'networkError',
  URL_IS_ALREADY_IN_THE_LIST: 'notOneOf',
  FIELD_IS_REQUIRED: 'required',
  URL: 'url',
  INITIALIZING: 'initializing',
  FILLING: 'filling',
  FAILURE: 'failure',
  SUBMITTED: 'submitted',
  SUCCESS: 'success',
};
