export default {
  rssWrapper: document.querySelector('.rss-wrapper'),
  form: document.querySelector('form'),
  input: document.querySelector('input[type="url"]'),
  languages: document.querySelectorAll('.language'),
  submitBtn: document.querySelector('button[type="submit"]'),
  siteDescription: document.querySelector('.site-description'),
  exampleUrl: document.querySelector('.example-url'),
  feedbackField: document.querySelector('.feedback'),
  modalTitle: document.querySelector('.modal-title'),
  modalBody: document.querySelector('.modal-body'),
  openFullArticle: document.querySelector('.open-full-article'),
  closeModalBtn: document.querySelector('.close-modal-btn'),
  createdBy: document.querySelector('.created-by'),
};
